# Generated by Django 4.2.4 on 2023-08-05 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="comments",
        ),
        migrations.AddField(
            model_name="comment",
            name="publication",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="publications.publication",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publication",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="post/"),
        ),
    ]
